# Generated by Django 5.1.2 on 2024-11-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_student_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_notification',
            old_name='staff_id',
            new_name='student_id',
        ),
    ]
