# Generated by Django 5.1.2 on 2024-11-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_attendance_attendance_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_report',
            old_name='subject_id',
            new_name='student_id',
        ),
    ]
